### PR TITLE
[WIP] adding more fuzzing targets

### PR DESCRIPTION
**Pull request by stusmall**
First pass at #28 with a test case for the first finding.  I'll add more fuzz targets

### CODE REVIEW

**Comment by mcginty** [comment]
Awesome, thanks! Do you have any feelings on libfuzzer vs. honggfuzz? You might have noticed there's also an `hfuzz` folder in the repo right now that uses the cargo-hfuzz wrapper that's basically the same as cargo-fuzz.

**Comment by stusmall** [comment]
Ah!  #28  was about more cases not different fuzzing tools?  I have no strong opinions.   I'll set them up with hfuzz instead.

**Comment by mcginty** [comment]
sounds good!

**Comment by mcginty** [comment]
wow, didn't realize you force-pushed the changes a while back! rebased your commit and merged it - thanks so much again and nice find!

**Pull request closed without merging**
