### PR TITLE
Cargo.toml: Update rand and rand_core to 0.8 and 0.6

### PR DESCRIPTION
**Pull request by mxinden**
See [rand changelog](https://github.com/rust-random/rand/blob/master/CHANGELOG.md) and [rand_core changelog](https://github.com/rust-random/rand/blob/master/rand_core/CHANGELOG.md).

Thanks for maintaining `snow`!

### CODE REVIEW

**Comment by mcginty** [comment]
Thanks!

**Comment by mxinden** [comment]
Thanks @mcginty for merging this pull request, updating all remaining outdated dependencies and cutting a release.

As far as I can tell `v0.7.3` includes breaking changes and should thus not have been a patch release, but a minor release (`v0.8.0`). More specifically this crate exposes parts of `rand` on its public API. `rand` introduced breaking changes between `v0.7` and `v0.8` and thus `snow` introduces breaking changes between `v0.7.2` and `v0.7.3`. The `v0.7.3` `snow` release thus breaks any builds directly depending on both `snow` and `rand`, e.g. the [rust-libp2p project](https://github.com/libp2p/rust-libp2p/pull/1954#pullrequestreview-590076408).

@mcginty could you yank `v0.7.3` and instead release the same source code as `v0.8.0`?

**Comment by mcginty** [comment]
@mxinden oh wow, yep. Yanked. I'll hold these changes until v0.8.0 along with these last few open PRs.

Sorry if that caused any annoyances in your project.

**Comment by mxinden** [comment]
> Yanked

Thank you for the swift resolution.

> I'll hold these changes until v0.8.0 along with these last few open PRs.

Sounds good to me.

**Pull request merged**
