### PR TITLE
Bump aes-gcm and chacha20poly1305

### PR DESCRIPTION
**Pull request by kayabaNerve**

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@mcginty Any chance this could be merged (and released?)

**Comment by kayabaNerve** [comment]
I just was going through my dep tree, looking for anything I could help out by bumping and found this again. Ping @mcginty, as a friendly reminder, if you have the time :)

**Comment by kayabaNerve** [comment]
I am shocked to discover I have once again noticed this, once again gotten to work on a quick commit to help out and contribute, and once again noticed I already did. 

I really should work on improving my memory, yet at least it's a decent reminder to ping @mcginty :sweat_smile:

**Comment by mcginty** [comment]
Ahhhh my bad!!

**Pull request merged**
